spatialdev/urban-carnivore-spotter

- functions/index.js
When running `firebase deploy --only functions`, I got the following errors:
This PR fixes those so we can deploy our functions to Firebase.
> Fix linting issues

- src/components/FormMap.js
This PR fixes a small bug where the location of the pin resets with changing fields.
> Small Map Bug Fix

- src/App.css
- src/components/Footer.js
- src/components/Form.js
- src/components/MobileHeader.js
- src/components/ReportViewer.js
- src/index.css
This PR fixes up some more styling and also fixes the form route for consistency on desktop and mobile. Previously, the mobile form wasn't been pushed to a route and the component was directly rendered. This PR fixes this and now adds logic for which to render based on screen width.
> More Style Updates and Fix Form Route

- package-lock.json
- package.json
- src/components/Form.js
This PR adds a dialog that pops up when a user submits a form. 
Currently, the flow is:
- Submit POST request to google cloud functions. When we get a status 200 response...
- Open "thank you" dialog. When the dialog is closed by the user...
- Navigate back to the main map page
I'm open to suggestions on this. It also looks pretty bare-bones at the moment -- maybe it'd be worth bringing Holly in on it, actually.
> "Thanks for submitting" Dialog

- package-lock.json
- package.json
- src/index.js
This adds the deploy script so it's easy to deploy new updates in the future. Also this handles routing from the enpoint `/urban-carnivore-spotter/...` by adding `basename="urban-carnivore-spotter"` to the `BrowserRouter`.
> Make this easily deployable

- functions/index.js
When we're displaying the filter options to users, there needs to be a list of all neighborhoods. I've updated the API structure to make this possible. Nothing is hooked in on the front end yet, but I want to get some 👀 on the structure to make sure this makes sense. 
The idea is to build a structure that looks like this in our cloud firestore:
```
uniques: {
neighborhood: {
values: [ "Unique", "values", "here" ]
}
},
reports: {...}
```
I got the idea to do it this way from [this stackoverflow post](https://stackoverflow.com/questions/48024410/how-to-get-all-unique-values-from-firestore-collection) -- basically, we have a separate document that keeps our lists of unique values, and update it whenever we come across a new unique value. This gives us fast lookup of the unique values as well …
> Add API structure to get all neighborhoods

- functions/index.js
PR #20 failed the linter when I tried to deploy the functions, because I forgot to run `npm run lint` before opening the PR 🤦‍♂ 
This fixes that, so we can deploy and continue improving the neighborhood functionality.
> Fix linting issues with neighborhood API

- package.json
- src/App.css
- src/components/DesktopHeader.js
- src/components/MobileHeader.js
This PR removes the hamburger menus from both the mobile and desktop headers.
> Remove Hamburger Menus

- src/components/ListCard.js
- src/components/ListView.js
- src/components/MapView.js
- src/components/PointTooltip.js
- src/components/ReportViewer.js
This PR adds the functionality to view individual report from both the feature pop up and list card. I have added it as a simple link. Styling for this will be added along with the pop up styling PR.
> Hook up ReportViewer on Map PopUp and ListCard

- functions/index.js
This modifies the `getReports` and `addReport` endpoints.
getReports now always automatically filters out data that either:
- doesn't have a `time_submitted` field
- has a `time_submitted` field less than a week old
addReports now always automatically adds a `time_submitted` field (or overwrites the existing field) with the current time before adding the report to firebase.
There was also an unused import at the top of the file so I got rid of it.
> Automatically add time_submitted, filter out last week's submissions

- src/components/ListView.js
- src/components/MapView.js
This PR adds a couple of styling to the navigation, list view and legend buttons and replace the map icon on ListView page to material icon "Place" button. This is to match the original comps.
> Map Button Styling

- src/components/ReportViewer.js
This PR adds the neighborhood, number of species fields to the report and takes out the index (top right corner) from the image.
> Small updates to ReportViewer

- src/components/Form.js
- src/services/FilterService.js
Minor fixes:
- I fixed a bug where turning off "other" wouldn't actually remove any other entries from the map/list
- Users now cannot select a date in the future when submitting a sighting.
> Date and Filter fixes

- functions/index.js
Really quick update so that my personal email stops getting notifications whenever someone submits a report 🎊 
No UI changes.
> Send emails to seattlecarnivores@gmail.com

- src/components/Form.js
This PR addresses the updates to the Animal Behavior Questions as requested by John in Trello. Following are the updates:
- Add option that states “The animal walked or moved away” to the “How did it react” question.
- Add “There was no interaction” option to the “Was there an interaction with observer” question. Make it the default option?
- Add sleeping, moving, foraging, climbing, running, and “other” options to the “What was it doing?” question.
- In the “How did it react?” section change the "Stood ground – uninterested in observer" option to “Animal ignored or was uninterested in observer.” Stood ground seems to confrontational.
- In the “How did you react?” section add an "I walked away" option.
- In the "Was there an interaction?" section add an "I walked away" option.
> Update Animal Behavior Questions

- functions/index.js
This comments out the waiting period logic so we don't accidentally deploy the waiting period to production 😬
> Comment out week waiting period logic

- src/App.css
- src/components/ReportViewer.js
This PR adds some UI updates to the individual report page. It now looks like below:
Desktop:
Mobile:
> Add Styling to Individual Report

- src/components/MapView.js
- src/components/PointTooltip.js
This PR adds a close button in the pop up box. 
Desktop:
Mobile:
> Close Button in Pop Up

- src/components/MapView.js
- src/services/ColorService.js
Based on recent request from Kodi, the colors for different species have been updated and a border has been added to the markers.
> Update Species Color and Add Marker Border

- package.json
- src/App.js
- src/components/Form.js
- src/components/ListView.js
- src/components/Main.js
- src/components/MapView.js
- src/components/MediaDisplay.js
- src/components/ReportViewer.js
- src/components/ResourceCard.js
- src/components/Resources.js
This PR adds the basic GA integration to track page views.
> Add Google Analytics 

- src/App.css
- src/components/MapView.js
Desktop: 
Mobile:
Take a look and let me know if you see anything that should be changed!
> update legend to toggle in place rather than in dialog

- functions/index.js
- src/components/Form.js
PR includes re adding the  week's filter and update form button color.
> Update Week Logic and Form Submit Button Color

- src/components/MediaUpload.js
- src/components/Uploader.js
Problem: Site won’t allow iphone photos to be selected.
Solution: Change file acceptType from images/* to image/*
> Fixes image upload bug
