functions/index.js, functions/package.json, package.json
This PR updates the 'getReports' function to handle location based querying. Turf library is used to compute the distance between the location of interest and locations fields in db. All locations that are in 1 mile distance to the location given in get request will be fetched. We can update the distance limit based on user input later; for now, I have used a 1 mile radius as the max limit.
Testing:
Firebase serve and pinging the end point by location. Example:
http://localhost:5000/seattlecarnivores-edca2/us-central1/getReports?location=53.29012,36.59229
=> Add filter by zoom level option 

src/App.css, src/components/DesktopHeader.js, src/components/ListView.js, src/components/MobileHeader.js
This PR addresses a couple of styling issues that I've noticed, namely the following: 
- The list view background is too dark and doesn't extend all the way down the list on mobile or desktop, and it's appearing in the desktop form view when it shouldn't:
- The form view gets blocked by the header on desktop since the header is `position:absolute;` and takes up no DOM space:
I've addressed these issues by making the headers and footers `position: sticky` instead of `position:absolute`, expanding the height of the `Main` div, and creating a special background div for the list view with a lighter background color. See the results:
- Form view now has a white background as expected:
- List view looks good when scrolled all the way to the top on desktop and mobile:
- Mobile list view looks …
=> Fix some CSS issues

src/components/Form.js
The add-media buttons don't have a hook between a user clicking on the box and opening the file select dialog, so I wasn't able to add the permission dialog at that point.
However, I was able to add a permission dialog upon hitting the upload button, which looks like this:
The user experience for this part of the form is still a little weird -- if we end up having time we might want to look into this. Even just a little bit of text showing that there are some files "on deck" but not actually added to the report might be helpful.
=> Add a permission dialog before uploading media to firebase

src/App.css, src/components/ListView.js
This PR adds a filter view to the desktop list view. In order to make it look good, I shrunk the default card size and used some [@media magic](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) to make it resize/stretch properly without overlapping at a variety of sizes. We can adjust these numbers if we find a spot where it looks gnarly, but I quickly ran through a couple and it looked decent. 
In an ideal world, the filter would actually have a static position displayed by some kind of flex thing, but I had a lot of trouble getting that running cleanly. So instead it's positioned absolute and then we just adjust the left margin of the list view as the window shrinks/expands. I'm not a huge fan of this solution but it seems to do the trick.
**Screenshots:**
Big desktop view: …
=> List view has a filter on desktop, and it's responsive

functions/index.js, functions/package-lock.json, functions/package.json
This PR wraps up automatic emails. Currently they're directed at my personal email, but it's really easy to switch that around.
For the sender, I signed up for a simple gmail account -- talk to me if you'd like the login information, or you can get the username and password by running `firebase functions:config:get`.
We should eventually do the following things:
- move the report_url_stub so we can deploy this for production and staging easily
- update the email to a more professional-looking account
- update the recipients to whoever the zoo wants
An email from this service looks like this:
I've verified that the link works properly.
=> Automatically send emails upon submissions

src/components/ListView.js
Now, the list view sorts by submission time!
Looks the same as before, so no screenshot included. I verified this worked by adding an entry directly into the database with a really old submission time and verifying that it appeared at the bottom of the list.
=> List view auto-sorts

src/components/Footer.js, src/components/FormMap.js
The form map is pretty hard to use on mobile at the moment, and this makes it a little better:
- Increased the radius of the draggable button so it'll be easier to start a drag gesture.
- Made the form drawer not swipeable on mobile -- I kept on accidentally closing the form while scrolling around whenever I hit some lag. I think having the submit at the bottom and the x at the top is good enough but we can discuss.
- Turned dragPan off for the map. So whenever a drag happens on the map it's clearly moving the dot and not panning the map.
- The map listens for onTouchMove events and blocks them from propagating, so moving your finger around on the map doesn't scroll the whole page.
We could also consider doing something where the marker stays still in the center and you drag the map …
=> Mobile Form Map Experience Improvements

src/components/Form.js
The form page now automatically requests the user's geolocation and populates the map and neighborhood information accordingly. Also the default location is now the zoo instead of the middle of downtown.
Looks like this:
and then after hitting "Allow":
=> Automatic geolocation on Form page

src/components/Form.js, src/components/FormInfoDialog.js
This sets an arbitrary limit of 1MB on the size of files that a user can upload. If a user uploads a set of files larger than 1MB, we pop up a dialog that requests that the user pick a different set of files. 
The UX here is a little weird because the user has no indication of what files are "on deck" when they hit upload. Something to think about. I also refactored the dialogs a bit since there was a lot of shared code between the various popups on the form -- now, we have a generic FormInfoDialog component that we can populate with a variety of information. 
This is what the popup looks like:
=> Limit the total size of uploaded files to 1MB

package.json, src/App.css, src/components/MapView.js, src/components/PointTooltip.js
Cleans up the map popup a little bit, reworking the structure a tiny bit:
At the moment, you can click a feature to display a popup and click the popup anywhere except the arrow to close it. In the future we should handle clicking on the map but not on a feature to close the popup as well. I took a stab at it but it's pretty tricky and I ran out of time -- we can come back to it later.
=> Styling and behavior on the popup

package-lock.json, package.json, src/components/FilterCheckboxes.js, src/components/FilterDrawer.js, src/components/MapView.js, src/components/MobileHeader.js, src/components/ResizableIconButton.js, src/services/FilterService.js, src/store/reducers.js
This makes a couple of styling/functionality changes to the filters:
- Clicking "all" is a little more intuitive now. The "all" button is automatically selected when all options have been selected, and toggling the button toggles all of the other options. @sayas01 I think you recommended something like this earlier -- great call. 
- On safari, the options were re-ordering whenever a user clicked a button. I've added an `order` field to ensure that the order remains constant.
- The expand buttons are now styled smaller, the map is in a better location, and I fixed some of the styling and spacing around the header
- Cancel is now named close. Do we even need this button? Not sure.
- Safari also had some issues with the header behaving properly with position: sticky, which I've addressed by …
=> Filter fixes

src/App.css, src/services/FilterService.js
This solves the bug we were getting with the list not filtering properly, which was introduced in #39. The changes are twofold:
- For any data, only display it/compare it against the filter if it has a species, neighborhood, confidence, and timestamp. This makes us a little more resilient against similar failures in the future. This also means that the data you're seeing on the page might be a little different, since many of the results we were displaying I either cleaned up in the process of trying to figure out what was going on, or doesn't contain all four of those components.
-  In addition, any report that has a species, but that species doesn't match the filter, won't break our filter-checking function by trying to get `undefined.value`. 
I also moved the filter to match the desktop …
=> Fix list filter bug (+ a minor css fix)

src/components/Form.js, src/components/MediaDisplay.js, src/components/Uploader.js
This makes some improvements to the experience as users upload media to their sightings.
I also fixed a bug where two extra entries were being appended to the end of the files, and confirmed that uploading still worked.
It looks like this: 
No upload button when no media is ready to be uploaded: 
Previews, remove files, and "confirm upload" which actually sends the media to firebase:
Loading spinner as the files are loaded into firebase:
Confirmation that files were actually uploaded:
=> Media upload UX improvements

src/components/Resources.js
This PR updates the css of Resources page in Mobile view. Following are the updates:
1) Increased spacing between the animal listings
2) Align the titles vertically center between the div lines
3) Update the background color of the page to F6F4F3 to make it stand out from the bottom panel
4) Make the titles little bit bigger and bold compared to the text in the body
These updates are for mobile view. Desktop resources page will be updated after Holly sends in the updated mocks.
=> Update Styling of Mobile Resources

src/App.css, src/components/Form.js, src/components/FormMap.js, src/components/MapView.js, src/components/StaticFormMap.js
This PR updates the design of the map element in the form on mobile. Currently both the desktop and mobile has the same design for form map that allows to pick a location of sighting.  Since drag and drop of pin on mobile sometimes results in dragging the pan, following updates have been made on mobile:
1) Form opens up with a non interactive or static map with an "Add Location" button.
2) On clicking the "Add Location" button, an interactive map opens up where the user can drag and drop pin to select location. The corresponding neighborhood gets displayed below the map. On clicking the "Done" button, the location gets updated on the map in the form. 
3) The map is non interactive with the marker on the selected location. Neighborhood is displayed below the map. The "Edit location" button …
=> Update FormMap on Mobile

src/components/Form.js
This is a quick fix to hide edit button when the DatePicker is selected.
=> Fix EditButton Visibility

src/components/DesktopHeader.js, src/components/MobileHeader.js, src/components/ScrollToTop.js, src/index.js
Now, when a user navigates to a new page, they automatically scroll to the top of the page. This prevents some issues we were having with the navigation disappearing on certain pages.
In addition, I've added the `<Sticky />` polyfill to the desktop and mobile headers so they stay visible while scrolling on Safari. For example:
Before, partially scrolled down on the list view:
After, partially scrolled down on the list view:
=> Automatically scroll to top of page and fix headers on scroll

src/components/ListCard.js, src/components/PointTooltip.js, src/components/ReportViewer.js, src/services/TimeService.js
We were displaying hours/minutes by printing the date.getHours() followed by date.getMinutes(), but we weren't padding the minutes. So 12:03 would display as 12:3, which isn't great.
This PR consolidates the logic to display time (which was spread out/repeated in a couple places), and pads the minutes so that the display looks right. We don't pad the hours, since 3:03 looks right (but 03:03 looks a little funny). Somewhere down the line we could look at doing AM/PM as well, but I decided to leave it in 24-hour time for now.
Before:
After:
=> Fix a issue with displaying time

src/components/Form.js, src/components/ResourceCard.js, src/components/SpeciesCardMobile.js
This fixes a couple things about the species carousel so that it works better on small devices:
- allows the carousel to shrink so that it doesn't require scrolling (which gets easily confused with swiping) on mobile devices with width around 350px:
- scrolling to the bottom of the slide doesn't reveal a black box anymore:
=> Update sizing of species carousel to work better for small devices

src/components/MapView.js
This addresses a couple of small issues with the map rendering logic that was causing weird behavior when zoomed out. 
1. If `reports` are null, then a totally different map is rendered. This was causing the icon buttons and filter box to not render until the reports check in the first time. I pushed the `!reports` logic further into the render in order to resolve this.
2. The `viewport` state was never being updated. I added some logic in `onMoveEnd` to update the state so whenever we move the map, the viewport is correct. I think this change isn't actually necessary given that we're now only rendering one map, but now the `viewport` state variable makes more sense IMO.
Proof of the map at a zoomed-out level:
=> Map zoom-out fix

src/components/MapView.js
This PR increase the size of the feature markers on the main map for both desktop and mobile. I have updated the size to be 7 (the marker on the form has the size 10).
Before:
After:
=> Update Map Marker Size

package-lock.json, package.json, src/App.css, src/components/Form.js, src/components/FormMap.js, src/components/StaticFormMap.js
This PR improves the mobile form map by allowing pinch-zoom and fixing the dialog so a user doesn't ever need to scroll.
Dialog closed:
Dialog open:
Desktop is unchanged:
In addition, clicking outside of the dialog now also closes it. 
This will be deployed at nachtm.github.io/urban-carnivore-spotter in a few minutes so you can play around with it live on mobile.
=> Mobile form map improvements

src/components/Resources.js, src/components/ResourcesDesktop.js, src/components/SpeciesCardDesktop.js, src/components/SpeciesCardMobile.js
Fixes a couple of typos and makes the scientific names italic. 
Italics & small fixes on the desktop resource page:
Small fixes on the mobile resource page:
Italics on mobile cards:
I'm not sure if "Seattle Carnivore Spotter" is exactly right--happy to change it around :)
=> Italics and small typos

src/components/Form.js, src/components/FormSelect.js
The current select dropdowns look great on desktop, but on mobile they have some issues with wrapping, take up a lot of the screen, and can't scroll (they can't scroll on desktop either but it doesn't seem like an issue). This PR refactors the select dropdowns into a FormSelect component for easier modification in the future, and uses the native select components on mobile. 
For example, this is what a long menu item looks like now:
There were also a couple extra bold tags floating around that I got rid of, so the expandable sections now look like the required sections:
Also, because #59 is an iOS-specific problem, I think it can be closed now -- this handles both problems!
=> Form - Select inputs now use native select on mobile

src/components/Form.js, src/components/FormInfoDialog.js
John had two requests related to the file submission workflow:
1. The file size is too small -- try 10MB.
2. "Unable to easily get rid of the error message. Maybe add X to upper right corner of every box."
This PR handles both of those -- instead of an X in the upper right corner, I added an "ok" button. Clicking outside of the box should still close the dialog as before, also.
As a possible future extension, we could look into a smarter workflow for handling video/audio, since I think storing raw video is still going to be a little heavy.
=> Form dialog defaults to ok button; increase file size limit

src/App.css, src/components/Form.js
The form's datepicker has a couple issues on mobile:
- Currently "Edit Location" floats over the datepicker, preventing the user from clicking on certain dates.
- The virtual keyboard pops up, obscuring part of the pop-up picker and making it nearly unusable.
This PR fixes both of these issues. The pop-up has a z-index of 1, so I gave the map a z-index of -1 and the button a z-index of 0. The virtual keyboard is an open issue with the react-datepicker component, but has a workaround here: https://github.com/Hacker0x01/react-datepicker/issues/942#issuecomment-485934975. Basically, setting the inner `<input />` to readOnly gets us what we want.
=> Date Input issues

src/App.css
The radio buttons were behaving weirdly on mobile iOS because their background was set to transparent. This removes that behavior.
I also glanced at the other input elements and verified that they looked normal.
Take a look at the new selected radio buttons from my phone:
=> Fix radio buttons

src/App.css, src/components/Footer.js
I migrated the css styling for the mobile footer into the Footer class, which had the added benefit of making the button show up as a thematically correct green.
At the same time, I played around with flexbox until the add new report button was centered properly. 
Notice that the window is exactly 500px wide and the middle of the plus lines up exactly with 250px:
=> Center the plus button

package-lock.json, package.json, src/components/Form.js, src/components/MediaDisplay.js, src/components/MediaUpload.js, src/components/Uploader.js
There were a couple issues with the media upload workflow: 
- If you upload an image, then upload a video, both get uploaded to firebase. However, `handleUploadSuccess` only associates the most recent file upload with the report. This manifests itself in a couple ways: the indicator would say "1 file uploaded" despite there being two files uploaded, and only one type of media shows up in the report viewer after the report is submitted. I updated `handleUploadSuccess` to keep track of previous uploads in addition to the current upload.
- Some browsers respect EXIF rotation data, causing some images to rotate on some browsers. Unfortunately there isn't a standard solution out there for this. On the plus side, the compression library (see below) strips out EXIF data as part of the …
=> Compress images, add progress indicator, and fix a couple issues

package-lock.json, package.json, src/components/Main.js, src/components/SplashPage.js, src/index.js
The first time that a user visits any page, we now have a dialog that pops up and explains the project. When the dialog is closed, we add a cookie "visitedBefore". The dialog looks for that cookie, and if it isn't present, displays itself. After we've visited the page once, notice the visitedBefore cookie:
I have screenshots on the map page but have confirmed that this shows up on any page, as long as it's the first page that the user has visited. 
Looks like this on desktop:
On mobile (the dialog is scrollable):
=> Add a splash page + cookie support

src/App.css, src/components/ReportViewer.js
Uses regex to extract the media type from the media url returned from firebase. If the video format is supported then we display an html5 video tag - otherwise we fallback to a simple img.
=> Adds support for video playback when viewing a report

functions/index.js, functions/package-lock.json, functions/package.json, src/components/Form.js
Before, the new report notification email was kind of a mess:
Now, it looks nice:
In particular, after discussion with the zoo folks, they requested an easier-to-look at layout with the following information:
- report ID
- media uploaded (the quicker it is to scan through, the better)
- neighborhood
- comment fields (anywhere that a user can enter text
In addition, they requested that we move from a 7-day waiting period to a 10-day waiting period. I've updated the (commented-out) filter in our cloud function, and updated the notification to users when they submit a sighting.
=> Prettify the notification email

functions/index.js, functions/package-lock.json, functions/package.json
This updates the email-notification code to include a cron job to send a table of jobs submitted in the last week. Right now it's set to send an email at midnight every night, so we can test the cron-triggering.
To test I had switched to an HTTP trigger, which produced these results:
Weekly digest:
Individual report:
As soon as this gets merged in, we can verify that it sends the email at midnight as expected, and then switch it to a weekly notification.
=> Weekly Digest Email

src/components/Form.js, src/components/ResourcesDesktop.js
There were a couple of outstanding issues from John's feedback.
- "Hard to understand that you can scroll past the map to understand more questions"
- This PR moves the map to the first question, so there's space below for more questions to appear. Also, there's no submission button until the bottom so the user should be able to figure out that they need to scroll.
- "On a laptop browser, it looks like the "Seattle Urban Carnivore Project" and "Contact Us" headings are part of the identification tips information."
- This PR adds a little bit of padding between the three topics, and adds an `<hr/>` between them.
=> Switch map order and separate species/other resources

public/index.html, public/manifest.json, src/App.css, src/components/DesktopHeader.js, src/components/MobileHeader.js, src/components/Resources.js, src/components/ResourcesDesktop.js
WPZ wants the app to be called Carnivore Spotter. So, this PR updates the name accordingly. 
I also moved the title a little further left at a couple of breakpoints on desktop which I think will address their concerns about the name and the logo overlapping.
There's also the "Urban Carnivore Project," which I think remains the same. If needed, we could update those references to Carnivore Spotter as well.
Some screenshots:
=> Urban Carnivore Sightings -> Carnivore Spotter

functions/index.js
I set the weekly digest to send an email every night in order to verify that it worked properly. At midnight last night, this email was sent out:
This updates the frequency so now it is 12:10AM on Tuesday mornings (the zoo said they would likely check on Tuesdays and Thursdays).
=> Weekly digest actually weekly

functions/index.js
The zoo wants emails to go to seattlecarnivores@zoo.org, so this PR changes the destination address to match. 
In addition, I've added a species column. Looks like this:
=> @zoo.org, show species

src/components/Form.js, src/components/MediaDisplay.js, src/components/MediaUpload.js
The changes in #66 didn't quite address the issues with mediaPaths. Basically, the `files` object for each Uploader remembers its own files, so uploading file A, then file B gives a mediaPaths object of [A, ...[A, B]] -> [A, A, B] which is not what we want.
Instead, now we're keeping track of each type of media separately, and only combining them on actual upload. 
Now, we get:
- Upload 1 video, upload 1 image -> 2 files uploaded (this was working as of #66 but was broken before)
- Upload 1 image, upload another image -> 2 files uploaded (before this PR, this would report 3 files uploaded)
=> Fix uploaded successfully count

firebase.json, package.json
`npm run deploy` now deploys to our [live production site](https://carnivorespotter.org/) 🎉 
I left in the old deploy script as `npm run deploy-gh-pages` in case we want to test things out before going external with them. Eventually we should have a staging version of cloud functions (and potentially the firestore as well).
Verified that it works with `npm run deploy` which you can see at the link above!
=> Deploy to Firebase

package-lock.json, package.json, src/App.css, src/components/FilterDrawer.js, src/components/FormMap.js, src/components/Main.js, src/components/MapView.js, src/components/StaticFormMap.js, src/components/UnsupportedBrowserNotice.js, src/index.js
This makes a couple of fixes to the app to make it (semi) compatible with Internet Explorer. 
1. Object.entries [is not supported by IE](https://caniuse.com/#search=Object.entries) but we use it a couple places. Rather than jump down the rabbit-hole of fixing individual IE-incompatible lines, I pulled in a polyfill to address the issue. 
2. Older versions of IE aren't explicitly supported by mapbox. I'm not sure whether we actually ran into any cases of this, since point 1 broke the experience for all IE users before mapbox even got involved. We now detect browsers that mapbox doesn't support, and show them a little popup--a "please use a more modern browser" type message. We also don't try to load the maps if we know they'll fail, so the users can at least see the rest of the app.
3. IE …
=> Compatible with IE

src/components/MapView.js
Current version adds a new mapbox layer for each species. With increase in the reports, rendering of the map became slower. This PR updates the MapView component to use a single layer for all the features. Verified that the map renders much faster than what we have now.
Credits to @danielduhh for his help in fixing this issue!
=> Render All Features on Same Layer

functions/index.js
Users sometimes enter personal information (including contact info and names) in their report submissions. We don't display this information anywhere on the app, yet our `getReports` endpoint includes that information in its response:
[{"id":"TxK9BVEWzCobjM2LwghV","data":{"generalComments":"First sighting of this adult coyote in our yard. Has been in and out for the past week. ","neighborhood":"Unknown","animalFeatures":"",**"contactEmail":"REDACTED@REDACTED"**,"mapLng":-122.306567,**"contactPhone":"REDACTED"**,"conflictDesc":"","reaction":"",**"contactName":"REDACTED"**,"carnivoreConflict":"","vocalizationDesc":"","numberOfDogs":"","vocalization":"","carnivoreResponse":"","numberOfYoungSpecies":"0","animalEating":"","timestamp":"2019-08-23T00:30:00.000Z","mapLat":47.700826,"animalBehavior …
=> API only send the information we actually display

functions/index.js, functions/package.json
Node.js 8 has been deprecated as of June 8 2020 and Firebase does not support Node.js 8 functions to be executed starting Feb 2021. This Pr updates the node version to 10. It also includes renaming couple of firebase functions for readability.
=> Update Node Version
